fix(compactor): fix metrics report error
risingwavelabs/risingwave pull request #10654
Opened 2023-06-29 09:34 UTC by Little-Wallace

I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- metrics `remote-io` duration of compact task does not show correctly.
- it is not necessary for compactor to show metrics of every instance.

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

## Documentation

- [ ] My PR contains user-facing changes.

<details><summary>Click here for Documentation</summary>

### Types of user-facing changes

Please keep the types that apply to your changes, and remove the others.

- Installation and deployment
- Connector (sources & sinks)
- SQL commands, functions, and operators
- RisingWave cluster configuration changes
- Other (please specify in the release note below)

### Release note

</details>

2023-07-03 06:10 UTC, hzxa21 approved these changes

2023-07-11 06:20 UTC, Little-Wallace commented
<img width="1998" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/16376959/ad2f7b5f-61fe-4c3c-9f10-a56f1fdfc14a">

2023-07-11 06:28 UTC, Li0k approved these changes

2023-07-11 06:46 UTC, Li0k commented on grafana/risingwave-dev-dashboard.dashboard.py
> +            "Bloom-Filter Miss Rate",
What does the modified metrics mean?

2023-07-11 06:48 UTC, Li0k requested changes
Can we remove the Miss rate ?

2023-07-11 06:53 UTC, Li0k approved these changes

2023-07-11 08:03 UTC, merged