chore(test): add more null range scan test
risingwavelabs/risingwave pull request #13566
Opened 2023-11-21 11:29 UTC by chenzl25

I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

- Resolve https://github.com/risingwavelabs/risingwave/pull/13524#discussion_r1400256185

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

2023-11-21 12:09 UTC, BugenZhao commented on e2e_test/batch/basic/null_range_scan.slt.part
> +create materialized view rev_t as select * from t order by v desc;
We should also drop the mv and table.

2023-11-21 13:03 UTC, stdrc requested changes
Should also consider `NULLS FIRST|LAST`

2023-11-21 14:08 UTC, chenzl25 commented
> Should also consider `NULLS FIRST|LAST`

Yes, we should. I have already seen your PR. Thanks!

2023-11-22 02:39 UTC, stdrc approved these changes

2023-11-22 03:50 UTC, merged