doc(dev-guide): note good first issue
risingwavelabs/risingwave pull request #19543
Opened 2024-11-22 10:05 UTC by xxchan

I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

## Checklist

- [ ] I have written necessary rustdoc comments
- [ ] I have added necessary unit tests and integration tests
- [ ] I have added test labels as necessary. See [details](https://github.com/risingwavelabs/risingwave/blob/main/docs/developer-guide.md#ci-labels-guide).
- [ ] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [ ] My PR contains breaking changes. (If it deprecates some features, please create a tracking issue to remove them in the future).
- [ ] All checks passed in `./risedev check` (or alias, `./risedev c`)
- [ ] My PR changes performance-critical code. (Please run macro/micro-benchmarks and show the results.)

- [ ] My PR contains critical fixes that are necessary to be merged into the latest release. (Please check out the [details](https://github.com/risingwavelabs/risingwave/blob/main/CONTRIBUTING.md))

## Documentation

- [ ] My PR needs documentation updates. (Please use the **Release note** section below to summarize the impact on users)

## Release note

If this PR includes changes that directly affect users or other significant modifications relevant to the community, kindly draft a release note to provide a concise summary of these changes. Please prioritize highlighting the impact these changes will have on users.

</details>

2024-11-22 10:06 UTC, stdrc requested changes
description

2024-11-22 10:06 UTC, xxchan commented
> description

no need

2024-11-22 10:26 UTC, xxchan commented on docs/dev/src/contributing.md
> +Related developers may not directly notice your PR. You can find developers who recently edited
```suggestion
Related developers may not directly notice your PR. To get your PR merged sooner, you may find reviewers on your own. You can find developers who recently edited
```

2024-11-23 06:26 UTC, kwannoel commented on docs/dev/src/contributing.md
> +
Shall we also refer them to community slack?

2024-11-23 06:26 UTC, kwannoel approved these changes
LGTM, thank you

2024-11-23 06:41 UTC, stdrc approved these changes

2024-11-23 08:53 UTC, merged