fix: force user specify at least one pk when create debezium source
risingwavelabs/risingwave pull request #5307
Opened 2022-09-13 09:47 UTC by tabVersion

Signed-off-by: tabVersion <tabvision@bupt.icu>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

***PLEASE DO NOT LEAVE THIS EMPTY !!!***

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

as title, add a pk check in the frontend, will reject req if pk not provided

```
ERROR:  QueryError: Protocol error: Primary key must be specified when creating source with row format debezium.
```

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

~~- [ ] I have written necessary rustdoc comments~~
~~- [ ] I have added necessary unit tests and integration tests~~
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)

fix #5248

2022-09-13 10:53 UTC, nanderstabel commented on src/frontend/src/handler/create_source.rs
> +    };
```suggestion
    let has_pk = stmt.constraints.iter().any(|cons| {
        match cons {
            TableConstraint::Unique { is_primary, .. } => *is_primary,
            _ => false
        }
    });
```

2022-09-13 11:03 UTC, nanderstabel commented
Should we add this to `e2e_test/source/basic_test.slt`?:
```
statement error
create materialized source no_pk (
    id integer, 
    status varchar
) with ( 
    connector = 'kafka', 
    topic = 'no_pk', 
    properties.bootstrap.server = '127.0.0.1:29092', 
    scan.startup.mode = 'earliest'
) row format debezium_json;
```
And this to `scripts/source/test_data/`?
```
{"schema":{},"payload":{"before":{"id":1,"status":null},"after":{"id":1,"status":"COMPLETED"},"source":{"version":"1.4.2.Final","connector":"postgresql","name":"postgres","ts_ms":1662716476390,"snapshot":"false","db":"simple_db","schema":"public","table":"t","txId":490,"lsn":23871176,"xmin":null},"op":"u","ts_ms":1662716476717,"transaction":null}}
```

2022-09-13 11:37 UTC, tabVersion commented
> Should we add this to `e2e_test/source/basic_test.slt`?:
> 
> ```
> statement error
> create materialized source no_pk (
>     id integer, 
>     status varchar
> ) with ( 
>     connector = 'kafka', 
>     topic = 'no_pk', 
>     properties.bootstrap.server = '127.0.0.1:29092', 
>     scan.startup.mode = 'earliest'
> ) row format debezium_json;
> ```
> 
> And this to `scripts/source/test_data/`?
> 
> ```
> {"schema":{},"payload":{"before":{"id":1,"status":null},"after":{"id":1,"status":"COMPLETED"},"source":{"version":"1.4.2.Final","connector":"postgresql","name":"postgres","ts_ms":1662716476390,"snapshot":"false","db":"simple_db","schema":"public","table":"t","txId":490,"lsn":23871176,"xmin":null},"op":"u","ts_ms":1662716476717,"transaction":null}}
> ```

we already have a debezium related test in `scripts/source/test_data/debezium_log.1`. No need to setup a new topic for this.

2022-09-13 14:00 UTC, nanderstabel approved these changes
LGTM!

2022-09-13 15:50 UTC, BugenZhao requested changes

2022-09-13 15:50 UTC, BugenZhao commented on src/frontend/src/handler/create_source.rs
> +    let has_pk = stmt.constraints.iter().any(|cons| match cons {
The primary key can also be specified with column constraints. May check `row_id_column` for whether user pk exists.

2022-09-14 04:07 UTC, BugenZhao commented on src/frontend/src/handler/create_source.rs
> +        });
There seems no need to check table constraints any more. It has been resolved in `bind_sql_table_constraints`.

2022-09-14 04:07 UTC, BugenZhao commented on src/frontend/src/handler/create_source.rs
> +    let has_pk = row_id_index.is_none()
```suggestion
    let has_user_specified_pk = row_id_index.is_none()
```

2022-09-14 06:07 UTC, xiangjinwu approved these changes
Just fix the unused `TableConstraint` warning

2022-09-14 07:05 UTC, BugenZhao approved these changes

2022-09-14 07:07 UTC, yezizp2012 approved these changes

2022-09-14 07:41 UTC, merged