refactor(batch): move the storage access of `RowSeqScan` from the executor builder to the body
risingwavelabs/risingwave pull request #5832
Opened 2022-10-13 08:37 UTC by BugenZhao

Signed-off-by: Bugen Zhao <i@bugenzhao.com>

I hereby agree to the terms of the [Singularity Data, Inc. Contributor License Agreement](https://gist.github.com/skyzh/0663682a70b0edde7ae991492f2314cb#file-s9y_cla).

## What's changed and what's your intention?

This PR moves the storage access of `RowSeqScan` from the executor builder to the body, so the time measurement of "building executors" can be measured more preciously.

## Checklist

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Refer to a related PR or issue link (optional)
- Close #5270

2022-10-13 09:18 UTC, liurenjie1024 approved these changes
LGTM

2022-10-13 11:10 UTC, chenzl25 commented
The usage of future make the code not straightforward.  Ideally, I think the structure of `RowSeqScanExecutor` should contain something like `PkBound` so that it can construct an iterator during execution. While `new_boxed_executor()` just convert the proto into `PkBound`.
```rust
/// Executor that scans data from row table
pub struct RowSeqScanExecutor<S: StateStore> {
    chunk_size: usize,
    pk_len: usize,
    identity: String,

    /// Batch metrics.
    /// None: Local mode don't record mertics.
    metrics: Option<BatchTaskMetricsWithTaskLabels>,

    epoch: HummockReadEpoch,
    table: StorageTable<S>,

    scan_ranges: Vec<PkBound>,
}

struct PkBound {
    prefix: Row,
    bound: (Bound<Datum>, Bound<Datum>),
}
```

2022-10-14 06:39 UTC, chenzl25 requested changes

2022-10-14 06:39 UTC, chenzl25 commented on src/batch/src/executor/row_seq_scan.rs
> +            unreachable!()
It's a possible path. e.g. `ScanRange::full()` generated before.

2022-10-14 06:50 UTC, chenzl25 approved these changes
LGTM!

2022-10-14 07:42 UTC, merged